#!/usr/bin/env pwsh
# ================================================================
# install.ps1 — Fall Risk Platform Installer (Production)
# รองรับ: Windows Server 2019/2022, Windows 10/11 (64-bit)
# ต้องการ: Docker Desktop >= 4.x หรือ Docker Engine + Compose v2
# Run as: Administrator PowerShell
# ================================================================
#Requires -RunAsAdministrator

param(
    [string]$HosxpHost     = "",
    [string]$HosxpPort     = "3306",
    [string]$HosxpUser     = "sa",
    [string]$HosxpPassword = "",
    [string]$HosxpDb       = "hos",
    [string]$HospitalCode  = "10986",
    [string]$HospitalName  = "Sai Buri Crown Prince Hospital",
    [string]$FrontendPort  = "3030",
    [string]$BackendPort   = "8000",
    [string]$DbPassword    = ""
)

[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
$ErrorActionPreference = "Stop"
$ProjectDir = $PSScriptRoot

function Write-Step([string]$msg) { Write-Host "`n[INSTALL] $msg" -ForegroundColor Cyan }
function Write-OK([string]$msg)   { Write-Host "  + $msg" -ForegroundColor Green }
function Write-Warn([string]$msg) { Write-Host "  ! $msg" -ForegroundColor Yellow }
function Write-Fail([string]$msg) { Write-Host "  X $msg" -ForegroundColor Red; exit 1 }

# STEP 1: Check Prerequisites
Write-Step "Checking Prerequisites..."
try { $v = docker --version 2>&1; Write-OK "Docker: $v" }
catch { Write-Fail "Docker not found. Install Docker Desktop from https://www.docker.com" }

try { $v = docker compose version 2>&1; Write-OK "Compose: $v" }
catch { Write-Fail "Docker Compose not found. Update Docker Desktop." }

try { docker info > $null 2>&1; Write-OK "Docker daemon running" }
catch { Write-Fail "Docker daemon not running. Start Docker Desktop." }

# STEP 2: Collect Configuration
Write-Step "Collecting Configuration..."
if (-not $HosxpHost) { 
    $HosxpHost = Read-Host "  HOSxP MySQL Host IP (เช่น 192.168.0.251)" 
}

$defaultPort = if ($HosxpPort) { $HosxpPort } else { "3306" }
$inputPort = Read-Host "  HOSxP MySQL Port [Enter เพื่อใช้: $defaultPort]"
if ($inputPort) { $HosxpPort = $inputPort } else { $HosxpPort = $defaultPort }

$defaultUser = if ($HosxpUser) { $HosxpUser } else { "sa" }
$inputUser = Read-Host "  HOSxP MySQL User [Enter เพื่อใช้: $defaultUser]"
if ($inputUser) { $HosxpUser = $inputUser } else { $HosxpUser = $defaultUser }

if (-not $HosxpPassword) {
    $sec = Read-Host "  HOSxP MySQL Password for '$HosxpUser'" -AsSecureString
    $HosxpPassword = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
        [Runtime.InteropServices.Marshal]::SecureStringToBSTR($sec))
}

$defaultDb = if ($HosxpDb) { $HosxpDb } else { "hos" }
$inputDb = Read-Host "  HOSxP Database Name [Enter เพื่อใช้: $defaultDb]"
if ($inputDb) { $HosxpDb = $inputDb } else { $HosxpDb = $defaultDb }

$defaultHcode = if ($HospitalCode) { $HospitalCode } else { "10986" }
$inputHcode = Read-Host "  Hospital Code 5 หลัก [Enter เพื่อใช้: $defaultHcode]"
if ($inputHcode) { $HospitalCode = $inputHcode } else { $HospitalCode = $defaultHcode }

$defaultHname = if ($HospitalName) { $HospitalName } else { "Sai Buri Crown Prince Hospital" }
$inputHname = Read-Host "  ชื่อโรงพยาบาล [Enter เพื่อใช้: $defaultHname]"
if ($inputHname) { $HospitalName = $inputHname } else { $HospitalName = $defaultHname }

if (-not $DbPassword) {
    $DbPassword = -join ((65..90)+(97..122)+(48..57) | Get-Random -Count 24 | ForEach-Object {[char]$_})
    Write-Warn "PostgreSQL password auto-generated — SAVE THIS: $DbPassword"
}

# Cryptographically secure 32-byte JWT secret compatible with Windows PowerShell 5.1 & PS 7+
$rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
$bytes = New-Object byte[] 32
$rng.GetBytes($bytes)
$JwtSecret = -join ($bytes | ForEach-Object { $_.ToString("x2") })
Write-OK "JWT secret generated"

# STEP 3: Write .env (Primary for Docker Compose)
Write-Step "Writing .env configuration..."
@"
# Auto-generated by install.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
APP_ENV=production
FRONTEND_PORT=$FrontendPort
BACKEND_PORT=$BackendPort
DB_PORT=5432

HOSPITAL_CODE=$HospitalCode
HOSPITAL_NAME=$HospitalName
HIS_TYPE=HOSXP

POSTGRES_DB=fall_risk_db
POSTGRES_USER=postgres
POSTGRES_PASSWORD=$DbPassword
DATABASE_URL=postgresql://postgres:${DbPassword}@db:5432/fall_risk_db

HOSXP_HOST=$HosxpHost
HOSXP_PORT=$HosxpPort
HOSXP_USER=$HosxpUser
HOSXP_PASSWORD=$HosxpPassword
HOSXP_DB=$HosxpDb

DEFAULT_THRESHOLD=0.47
AUTO_RETRAIN_THRESHOLD=50
MODELS_DIR=models_storage

DAEMON_POLL_INTERVAL=30
DAEMON_MIN_AGE=60

JWT_SECRET_KEY=$JwtSecret
JWT_EXPIRATION_HOURS=8
MAX_LOGIN_ATTEMPTS=5
LOCKOUT_MINUTES=15
"@ | Out-File -FilePath "$ProjectDir\.env" -Encoding UTF8 -Force
Write-OK ".env written"

# STEP 4: Write secrets.toml (Mounted into /app/secrets.toml)
Write-Step "Writing secrets.toml..."
@"
[hosxp]
host     = "$HosxpHost"
port     = $HosxpPort
user     = "$HosxpUser"
password = "$HosxpPassword"
database = "$HosxpDb"

[database]
url = "postgresql://postgres:$DbPassword@db:5432/fall_risk_db"

[ml]
default_threshold      = 0.47
auto_retrain_threshold = 50

[hospital]
hospital_code = "$HospitalCode"
hospital_name = "$HospitalName"
his_type      = "HOSXP"

[auth]
jwt_secret_key       = "$JwtSecret"
jwt_expiration_hours = 8
max_login_attempts   = 5
lockout_minutes      = 15
"@ | Out-File -FilePath "$ProjectDir\secrets.toml" -Encoding UTF8 -Force
Write-OK "secrets.toml written"

# STEP 5: Build images
Write-Step "Building Docker images (อาจใช้เวลา 5-10 นาที)..."
Set-Location $ProjectDir
docker compose build --no-cache
Write-OK "Images built"

# STEP 6: Start services
Write-Step "Starting services..."
docker compose up -d
Write-OK "Containers started"

# STEP 7: Wait for DB healthy
Write-Step "Waiting for PostgreSQL..."
$waited = 0
while ($waited -lt 90) {
    $s = docker inspect fall_risk_db --format "{{.State.Health.Status}}" 2>$null
    if ($s -eq "healthy") { Write-OK "PostgreSQL healthy"; break }
    Start-Sleep 3; $waited += 3
    Write-Host "  ... $waited s"
}

# STEP 8: Verify health
Write-Step "Verifying API health..."
Start-Sleep 5
try {
    $h = Invoke-RestMethod "http://localhost:${BackendPort}/healthz" -TimeoutSec 20
    Write-OK "healthz: $($h.status)"
    $r = Invoke-RestMethod "http://localhost:${BackendPort}/readyz" -TimeoutSec 20
    Write-OK "readyz: DB=$($r.checks.database) Model=$($r.checks.model)"
} catch { Write-Warn "Health check failed (system may still be initializing): $_" }

# STEP 9: Firewall rules
Write-Step "Adding Firewall rules..."
New-NetFirewallRule -DisplayName "FallRisk-Frontend-$FrontendPort" `
    -Direction Inbound -Protocol TCP -LocalPort $FrontendPort -Action Allow -EA SilentlyContinue | Out-Null
New-NetFirewallRule -DisplayName "FallRisk-Backend-$BackendPort" `
    -Direction Inbound -Protocol TCP -LocalPort $BackendPort -Action Allow -EA SilentlyContinue | Out-Null
Write-OK "Firewall rules added"

# STEP 10: Auto-start task
Write-Step "Registering auto-start task..."
$xml = @"
<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <Triggers><BootTrigger><Enabled>true</Enabled><Delay>PT30S</Delay></BootTrigger></Triggers>
  <Principals><Principal><RunLevel>HighestAvailable</RunLevel></Principal></Principals>
  <Actions><Exec><Command>docker</Command><Arguments>compose -f "$ProjectDir\docker-compose.yml" start</Arguments></Exec></Actions>
  <Settings><ExecutionTimeLimit>PT5M</ExecutionTimeLimit><StartWhenAvailable>true</StartWhenAvailable></Settings>
</Task>
"@
$xml | Out-File "$env:TEMP\fallrisk_task.xml" -Encoding Unicode
schtasks /Create /TN "FallRiskPlatform_Autostart" /XML "$env:TEMP\fallrisk_task.xml" /F 2>$null | Out-Null
Write-OK "Auto-start task registered"

$ip = (Get-NetIPAddress -AddressFamily IPv4 | Where-Object {$_.IPAddress -notlike "127.*" -and $_.InterfaceAlias -notlike "*Loopback*"} | Select -First 1).IPAddress

Write-Host ""
Write-Host "==================================================" -ForegroundColor Green
Write-Host "  Fall Risk Platform installed successfully!" -ForegroundColor Green
Write-Host "==================================================" -ForegroundColor Green
Write-Host "  Frontend:  http://${ip}:${FrontendPort}"
Write-Host "  API Docs:  http://${ip}:${BackendPort}/docs"
Write-Host "  Health:    http://${ip}:${BackendPort}/healthz"
Write-Host ""
Write-Host "  Login: ใช้ username/password จาก HOSxP"
Write-Host "  SAVE .env and secrets.toml — ห้าม commit ไฟล์นี้เข้า git"
Write-Host ""
